---
title: "Gaussian process models"
author:
- Eric Kalosa-Kenyon
date: "`r format(Sys.time(), '%d %B %Y')`"

abstract: In this report, I show some basic theory and applications for gaussian processes.

output:
  html_document:
    toc: yes
---

```{r echo=F}
rm(list=ls())
set.seed(33)

library(ggplot2)
library(MASS)
library(reshape)
```

# Basic deffinition
foobar

# Baby's first visualization
Below I depict discretized draws from a gaussian process.

```{r}
# Parameters
t = c(-1,1) # plotting range
D = 50*floor(abs(t[1]-t[2])) # number of evenlt spaced collocation points
K = 10 # number of curves
lkern = 0.1 # kernel length-scale hyperparameter
sigkern = 2 # kernel varaince hyperparameter

# Define kernel
kernel = function(x0, x1){
    # Using squared exponential loss
    return(sigkern^2 * exp(-1/2 * (x0-x1)^2 / lkern))
}

# Define mean function
mu = function(x){
    # Constant mean
    return(0*x)
}

# Collocate X values
xs = seq(t[1], t[2], length.out=D)

# Calculate covariance matrix
S = outer(xs, xs, kernel)

# Draw joint multivariate gaussian samples
ys = t(mvrnorm(K, mu = mu(xs), Sigma=S))

# Plot
plt_df = data.frame(x=xs, y=ys)
names(plt_df) = c("x", paste("GP", 1:K, sep=""))
plt_df_m = melt(plt_df, id=c("x"))
plt = ggplot(plt_df_m) +
    geom_line(aes(x=x, y=value, color=variable)) +
    labs(x="X", y="Y",
         title=paste(K, "draws from a gaussian process")) +
    scale_fill_discrete(name="Draw number")
```

```{r echo=F}
plt
```
